---
- name: start codedeploy-agent
  service:
    name: codedeploy-agent
    state: started
  become: yes

- name: stop codedeploy-agent
  service:
    name: codedeploy-agent
    state: stopped
  become: yes
